### ISSUE TITLE
English Documentation

### ISSUE THREAD

**Issue by fameoflight** [margox/braft-editor#125]
This looks pretty good any chance to get english documentation?

**Comment by margox** [comment]
Hi Hemant, I am very happy that you like this project, I've started to write project documentation in English, but I'm not sure when it will be done because my English is not very good and I've been very busy in recent months. I'm almost the only frontend developer of my company. Many company's things to do😅😅😆

**Comment by zomars** [comment]
Can we re-open this?

**Comment by GLuchtenberg** [comment]
@zomars I wish so

**Comment by pierre-H** [comment]
+1 😃

**Comment by charanjit-singh** [comment]
https://github.com/charanjit-singh/braft-editor Check out this for english translation
