### ISSUE TITLE
Braft-editor wont work in SSR webpack application?

### ISSUE THREAD

**Issue by dayrlism10** [margox/braft-editor#264]
![screenshot 2018-10-22 at 10 23 43 am](https://user-images.githubusercontent.com/38413388/47275760-ad352080-d5e4-11e8-846e-c824ea4ebfbb.png)

Hi there, 
braft editor wont really render into my application, does this plugin supported ssr application?
Or there is alternative that i can do in the webpack to render this plugin?

**Comment by margox** [comment]
Hi，I don't think it's an option to render an rich text editor on the server side, it's unnecessary, because it's not a component which only contains static contents, and the BraftEditor component uses some methods under the window object, such as getBoundingRectClient, to make sure the dropdown controls showing at a correct position.
You can use the [React No SSR](https://github.com/kadirahq/react-no-ssr) to prevent components from rendering on the server side.

**Comment by fenos** [comment]
@margox I was thinking to use this amazing editor with the `readOnly` flag of draftJS to actually render the content (without showing the controls) so that I feel way more secure then rendering HTML since users have the freedom to use the editor on the site.  

Although with this issue it prevents me to render the editor on the server side.

Even though the library does use of `getBoundingRectClient` it would be great if it could be wrapped around an if statement to check the existence of `window`

```
if (typeof window !== "undefined") {
   window. getBoundingRectClient()
}
```

Any suggestions on this?

**Comment by margox** [comment]
@fameoflight Hi, I just published a new version of braft-editor(v2.3.0), you may take a look, thanks so much for using this project, :)

**Comment by sherry-li-or** [comment]
"braft-editor": "^2.3.9", 一樣發生錯誤 :(

**Comment by GqiangQ** [comment]
// This is the problem that I used in nextjs project
// 这个是我在nextjs项目中使用出现的问题

import dynamic from 'next/dynamic'

// components/edit is Your custom components
// 这里是你自定义的组件，这个组件中是那个出现window或document is not defined 
const EditWithNoSSR = dynamic(import('components/edit'), {
  ssr: false
})

**Comment by HeJueting** [comment]
> // This is the problem that I used in nextjs project
> // 这个是我在nextjs项目中使用出现的问题
> 
> import dynamic from 'next/dynamic'
> 
> // components/edit is Your custom components
> // 这里是你自定义的组件，这个组件中是那个出现window或document is not defined
> const EditWithNoSSR = dynamic(import('components/edit'), {
> ssr: false
> })

`dynamic(() => import("../editor"), { ssr: false })`
